---
development:
  dialect: postgres
  database: simple_bank
  user: root
  password: secret
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/db_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable"}}
